// -----------------------------------------------------------------------
// Licensed to The .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// -----------------------------------------------------------------------

using Kerberos.NET.Crypto;
using Kerberos.NET.Entities;

namespace Kerberos.NET.Server
{
    /// <summary>
    /// Contains the state information of a FAST (RFC 6113) armored request
    /// used between the pre-validation and validation phases.
    /// </summary>
    public class FastState : PaDataState
    {
        /// <summary>
        /// The derived FAST armor key used to protect the tunnel.
        /// </summary>
        public KerberosKey ArmorKey { get; set; }

        /// <summary>
        /// The inner FAST request extracted from the armored envelope.
        /// </summary>
        public KrbFastReq InnerRequest { get; set; }

        /// <summary>
        /// A random key generated by the KDC to strengthen the reply key.
        /// </summary>
        public KerberosKey StrengthenKey { get; set; }

        /// <summary>
        /// The decrypted armor AP-REQ containing the ticket and authenticator.
        /// </summary>
        public DecryptedKrbApReq DecryptedArmorApReq { get; set; }
    }
}
