<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Kerberos.NET.Asn1CodeGen</RootNamespace>
    <LangVersion>9</LangVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="testdata\**" />
  </ItemGroup>

</Project>
