<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Kerberos.NET.CommandLine</RootNamespace>

    <RollForward>Major</RollForward>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>bruce</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>

    <Product>Kerberos.NET Command Line Tool</Product>
    <Description>A command line tool that manages the cross-platform, managed-code Kerberos Ticket parsing, validation, and authentication library Kerberos.NET.</Description>
    <PackageTags>security kerberos</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>

    <EmbeddedResource Update="Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kerberos.NET.PortableDns\Kerberos.NET.PortableDns.csproj" />
    <ProjectReference Include="..\Kerberos.NET\Kerberos.NET.csproj" />
    <ProjectReference Include="..\Samples\KerbDumpCore\KerbDumpCore.csproj"
                      Condition="'$(OS)' == 'Windows_NT'" />
  </ItemGroup>

</Project>
