//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerberos.NET.CommandLine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kerberos.NET.CommandLine.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line tooling for the Kerberos.NET library..
        /// </summary>
        internal static string BannerDescription {
            get {
                return ResourceManager.GetString("BannerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerberos Configuration File.
        /// </summary>
        internal static string ComandLine_KConfig_Config {
            get {
                return ResourceManager.GetString("ComandLine_KConfig_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string CommandLine_CachePath {
            get {
                return ResourceManager.GetString("CommandLine_CachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string CommandLine_Commands {
            get {
                return ResourceManager.GetString("CommandLine_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of configuration sections can be accessed through the dot operator (e.g. section.property)..
        /// </summary>
        internal static string CommandLine_Config_DotHelp {
            get {
                return ResourceManager.GetString("CommandLine_Config_DotHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties that would contain dots can be escaped with quotes (e.g. section.&quot;realm.name&quot;.property)..
        /// </summary>
        internal static string CommandLine_Config_DotHelpEscaped {
            get {
                return ResourceManager.GetString("CommandLine_Config_DotHelpEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration could not be processed.
        /// </summary>
        internal static string CommandLine_Config_Invalid {
            get {
                return ResourceManager.GetString("CommandLine_Config_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a configuration value..
        /// </summary>
        internal static string CommandLine_Config_SetEquals {
            get {
                return ResourceManager.GetString("CommandLine_Config_SetEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a configuration value..
        /// </summary>
        internal static string CommandLine_Config_SetEqualsNull {
            get {
                return ResourceManager.GetString("CommandLine_Config_SetEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append a new value or make the property into a list of values..
        /// </summary>
        internal static string CommandLine_Config_SetEqualsPlus {
            get {
                return ResourceManager.GetString("CommandLine_Config_SetEqualsPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a configuration value..
        /// </summary>
        internal static string CommandLine_Config_SetEqualsSpace {
            get {
                return ResourceManager.GetString("CommandLine_Config_SetEqualsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append a new value or make the property into a list of values..
        /// </summary>
        internal static string CommandLine_Config_SetEqualsSpacePlus {
            get {
                return ResourceManager.GetString("CommandLine_Config_SetEqualsSpacePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a configuration value..
        /// </summary>
        internal static string CommandLine_Config_SetSpaceNull {
            get {
                return ResourceManager.GetString("CommandLine_Config_SetSpaceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Configuration Path.
        /// </summary>
        internal static string CommandLine_ConfigPath {
            get {
                return ResourceManager.GetString("CommandLine_ConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Configuration Path.
        /// </summary>
        internal static string CommandLine_ConfigPath_Actual {
            get {
                return ResourceManager.GetString("CommandLine_ConfigPath_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Default Values.
        /// </summary>
        internal static string CommandLine_Defaults {
            get {
                return ResourceManager.GetString("CommandLine_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string CommandLine_Example {
            get {
                return ResourceManager.GetString("CommandLine_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set or review configuration settings at the default path..
        /// </summary>
        internal static string CommandLine_KerberosConfig {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all configuration options including default values..
        /// </summary>
        internal static string CommandLine_KerberosConfigCommand_All {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConfigCommand_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a path to a particular configuration file..
        /// </summary>
        internal static string CommandLine_KerberosConfigCommand_Config {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConfigCommand_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute a constrained delegation call with the provided parameters..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegation {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Principal Name of the backend service that should receive the delegated ticket..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_Delegated {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_Delegated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help text..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_Help {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm of the client for authentication..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_Realm {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Service Principal Name of the middle box..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_ServicePrincipalName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_ServicePrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the Service Principal of the middle box..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_ServicePrincipalNamePassword {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_ServicePrincipalNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sAMAccountName of the Service Principal of the middle box..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_ServicePrincipalSamAccountName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_ServicePrincipalSamAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Principal Name for client authentication..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_UserPrincipalName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_UserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display additional logging data for each stage during execution..
        /// </summary>
        internal static string CommandLine_KerberosConstrainedDelegationCommand_Verbose {
            get {
                return ResourceManager.GetString("CommandLine_KerberosConstrainedDelegationCommand_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch a GUI to decode Kerberos tickets..
        /// </summary>
        internal static string CommandLine_KerberosDecode {
            get {
                return ResourceManager.GetString("CommandLine_KerberosDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the ticket cache..
        /// </summary>
        internal static string CommandLine_KerberosDestroy {
            get {
                return ResourceManager.GetString("CommandLine_KerberosDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache file has been deleted..
        /// </summary>
        internal static string CommandLine_KerberosDestroy_Deleted {
            get {
                return ResourceManager.GetString("CommandLine_KerberosDestroy_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete cache file.
        /// </summary>
        internal static string CommandLine_KerberosDestroy_Error {
            get {
                return ResourceManager.GetString("CommandLine_KerberosDestroy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a path to a particular cache file..
        /// </summary>
        internal static string CommandLine_KerberosDestroyCommand_Cache {
            get {
                return ResourceManager.GetString("CommandLine_KerberosDestroyCommand_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides help information about commands..
        /// </summary>
        internal static string CommandLine_KerberosHelp {
            get {
                return ResourceManager.GetString("CommandLine_KerberosHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the name of the command to list helpful information about the command..
        /// </summary>
        internal static string CommandLine_KerberosHelpCommand_HelpCommand {
            get {
                return ResourceManager.GetString("CommandLine_KerberosHelpCommand_HelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain a cache a Kerberos Ticket-Granting-Ticket..
        /// </summary>
        internal static string CommandLine_KerberosInit {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an anonymous ticket..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Anonymous {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the name of a cache used to armor the current request..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_ArmorCache {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_ArmorCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the name of a cache to store and retrieve tickets..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Cache {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests canonicalization of the ticket principal name..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Canonicalize {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Canonicalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate a certificate and use PKINIT to authenticate the user..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Certificate {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the path to a configuration to use for initialization..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Config {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Credential not found.
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_CredNotFound {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_CredNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A realm cannot be determined based on the configuration or credential information..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_DomainRequired {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_DomainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat the principal name as an enterprise name..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Enterprise {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the encryption types that should be used in preferred order..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_ETypes {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_ETypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass values to Kerberos extensions..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Extension {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include additional addresses in the ticket request..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_ExtraAddr {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_ExtraAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a forwardable ticket..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Forward {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a ticket with addresses..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_IncludeAddresses {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_IncludeAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the KDC that should process this request..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_KdcHostname {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_KdcHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain a ticket using the provided keytab..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Keytab {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Keytab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a ticket with the provided lifetime..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_LifeTime {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_LifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not request a forwardable ticket..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_NoForward {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_NoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not request a proxiable ticket..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_NoProxy {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_NoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally provide the password to authenticate the user..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Password {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a proxiable ticket..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Proxy {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the realm name to authenticate against..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_RealmName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_RealmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew the requested TGT..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Renew {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a ticket that is renewable up to renewable-lifetime or infinite lifetime..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Renewable {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Renewable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a ticket that is renewable up to the requested lifetime..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_RenewLifetime {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_RenewLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate whether a PAC should be requested during authentication..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_RequestPac {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_RequestPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the connection cache..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Reset {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a service name to to use when getting tickets..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Servicename {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Servicename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a ticket starting from the provided time..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_StartTime {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain a ticket using the keytab located in the default location..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Usekeytab {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Usekeytab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The principal name to use otherwise uses the current system user..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_UserPrincipalName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_UserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request the TGT be sent to the KDC for validation..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Validate {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display verbose output..
        /// </summary>
        internal static string CommandLine_KerberosInitCommand_Verbose {
            get {
                return ResourceManager.GetString("CommandLine_KerberosInitCommand_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, create, and modify keytab files..
        /// </summary>
        internal static string CommandLine_KerberosKeytab {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Type.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_EType {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_EType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytab file deleted.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_FileDeleted {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_FileVersion {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerberos Version.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_KerbVersion {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_KerbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded Key Value.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_Key {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Length.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_KeyLength {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_KeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys in File.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_Keys {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Version.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_KeyVersion {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_KeyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Name.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_PrincipalName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_PrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_TimeStamp {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string CommandLine_KerberosKeytab_UnknownFile {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytab_UnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new key to the file..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Add {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the keytab file..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Delete {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optioanlly specify which Encryption Types should have keys generated..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_EType {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_EType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the keytab file to create, modify, or view..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_File {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sAMAccountName if the principal is a service account with SPN..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Host {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally provide the key as a base64 encoded value..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Key {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not attempt to get logon information from the KDC..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Offline {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally provide the password of the principal..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Password {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Principal Name (user or service) of the key to add..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Principal {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally specify type of principal name to use instead of detecting format..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_PType {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_PType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The realm of the principal of the key to add..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Realm {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the salt used to derive the key instead of computing it..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Salt {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the key when viewing details about the file..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Show {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display additional logging information..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Verbose {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the generated keytab can be used to authenticate a principal..
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_Verify {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification of the keytab failed because authentication failed. Maybe the password is wrong?.
        /// </summary>
        internal static string CommandLine_KerberosKeytabCommand_VerifyFailedCred {
            get {
                return ResourceManager.GetString("CommandLine_KerberosKeytabCommand_VerifyFailedCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the current list of tickets in the cache..
        /// </summary>
        internal static string CommandLine_KerberosList {
            get {
                return ResourceManager.GetString("CommandLine_KerberosList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the contents of the provided cache name..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_Cache {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show client debug information.
        /// </summary>
        internal static string CommandLine_KerberosListCommand_DescribeClient {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_DescribeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a service ticket for the provided SPN..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_Get {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all the caches for the current user..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_ListCaches {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_ListCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all cached tickets..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_Purge {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display ticket flags in short-form..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_ShortFlags {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_ShortFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the TGT of the current user..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_ShowTgt {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_ShowTgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify a Ticket-Granting-Ticket is present and valid in the cache..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_Test {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays all data about the cache..
        /// </summary>
        internal static string CommandLine_KerberosListCommand_Verbose {
            get {
                return ResourceManager.GetString("CommandLine_KerberosListCommand_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password of the principal or set password of another principal..
        /// </summary>
        internal static string CommandLine_KerberosPassword {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change succeeded for {0}..
        /// </summary>
        internal static string CommandLine_KerberosPassword_ChangeSuccess {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword_ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running kpasswd change password for {0}....
        /// </summary>
        internal static string CommandLine_KerberosPassword_Changing {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword_Changing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Credential not found.
        /// </summary>
        internal static string CommandLine_KerberosPassword_CredNotFound {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword_CredNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password for {0}: .
        /// </summary>
        internal static string CommandLine_KerberosPassword_NewPassPrompt {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword_NewPassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for {0}: .
        /// </summary>
        internal static string CommandLine_KerberosPassword_PassPrompt {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword_PassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password set succeeded for {0}..
        /// </summary>
        internal static string CommandLine_KerberosPassword_SetSuccess {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword_SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running kpasswd set password for {0}....
        /// </summary>
        internal static string CommandLine_KerberosPassword_Setting {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPassword_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the path to a configuration to use for initialization..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_Config {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide new password to set..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_NewPassword {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally provide the password to authenticate the user..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_Password {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The principal name to use otherwise uses the current system user..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_Principal {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the realm name to authenticate against..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_Realm {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the principal name of user to set password of..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_TargName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_TargName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the realm name of user to set password of..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_TargRealm {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_TargRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include detailed logging information in the kpasswd request..
        /// </summary>
        internal static string CommandLine_KerberosPasswordCommand_Verbose {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPasswordCommand_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate and ping a KDC for the provided user to get pre-auth details..
        /// </summary>
        internal static string CommandLine_KerberosPing {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate which realm the queried user belongs..
        /// </summary>
        internal static string CommandLine_KerberosPing_Realm {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPing_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Principal Name used to ping the KDC.
        /// </summary>
        internal static string CommandLine_KerberosPing_UserPrincipalName {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPing_UserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include detailed logging information about the ping request..
        /// </summary>
        internal static string CommandLine_KerberosPing_Verbose {
            get {
                return ResourceManager.GetString("CommandLine_KerberosPing_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays details about the current authenticated user..
        /// </summary>
        internal static string CommandLine_KerberosWhoAmI {
            get {
                return ResourceManager.GetString("CommandLine_KerberosWhoAmI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all available details about the current user..
        /// </summary>
        internal static string CommandLine_KerberosWhoAmI_All {
            get {
                return ResourceManager.GetString("CommandLine_KerberosWhoAmI_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally provide the path to the ticket cache file of the user to look up..
        /// </summary>
        internal static string CommandLine_KerberosWhoAmI_Cache {
            get {
                return ResourceManager.GetString("CommandLine_KerberosWhoAmI_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display claims for the current user..
        /// </summary>
        internal static string CommandLine_KerberosWhoAmI_Claims {
            get {
                return ResourceManager.GetString("CommandLine_KerberosWhoAmI_Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display group membership about the current user..
        /// </summary>
        internal static string CommandLine_KerberosWhoAmI_Groups {
            get {
                return ResourceManager.GetString("CommandLine_KerberosWhoAmI_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display logon information about the current user..
        /// </summary>
        internal static string CommandLine_KerberosWhoAmI_Logon {
            get {
                return ResourceManager.GetString("CommandLine_KerberosWhoAmI_Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include detailed logging information in the whoami request..
        /// </summary>
        internal static string CommandLine_KerberosWhoAmI_Verbose {
            get {
                return ResourceManager.GetString("CommandLine_KerberosWhoAmI_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for {0}: .
        /// </summary>
        internal static string CommandLine_KInit_PassPrompt {
            get {
                return ResourceManager.GetString("CommandLine_KInit_PassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Id.
        /// </summary>
        internal static string CommandLine_KList_BranchId {
            get {
                return ResourceManager.GetString("CommandLine_KList_BranchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string CommandLine_KList_Client {
            get {
                return ResourceManager.GetString("CommandLine_KList_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Client Details.
        /// </summary>
        internal static string CommandLine_KList_ClientDetails {
            get {
                return ResourceManager.GetString("CommandLine_KList_ClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Count.
        /// </summary>
        internal static string CommandLine_KList_Count {
            get {
                return ResourceManager.GetString("CommandLine_KList_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string CommandLine_KList_End {
            get {
                return ResourceManager.GetString("CommandLine_KList_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string CommandLine_KList_Flags {
            get {
                return ResourceManager.GetString("CommandLine_KList_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDC Called.
        /// </summary>
        internal static string CommandLine_KList_KdcCalled {
            get {
                return ResourceManager.GetString("CommandLine_KList_KdcCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Until.
        /// </summary>
        internal static string CommandLine_KList_RenewTime {
            get {
                return ResourceManager.GetString("CommandLine_KList_RenewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string CommandLine_KList_Server {
            get {
                return ResourceManager.GetString("CommandLine_KList_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Key Type.
        /// </summary>
        internal static string CommandLine_KList_SessionEType {
            get {
                return ResourceManager.GetString("CommandLine_KList_SessionEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string CommandLine_KList_Start {
            get {
                return ResourceManager.GetString("CommandLine_KList_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket EType.
        /// </summary>
        internal static string CommandLine_KList_TicketEType {
            get {
                return ResourceManager.GetString("CommandLine_KList_TicketEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string CommandLine_UnknownCommand {
            get {
                return ResourceManager.GetString("CommandLine_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string CommandLine_Usage {
            get {
                return ResourceManager.GetString("CommandLine_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string CommandLine_Version {
            get {
                return ResourceManager.GetString("CommandLine_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator Claims.
        /// </summary>
        internal static string CommandLine_WhoAmI_Claims {
            get {
                return ResourceManager.GetString("CommandLine_WhoAmI_Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string CommandLine_WhoAmI_Groups {
            get {
                return ResourceManager.GetString("CommandLine_WhoAmI_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not logged on. Try kinit first..
        /// </summary>
        internal static string CommandLine_WhoAmI_NoTgt {
            get {
                return ResourceManager.GetString("CommandLine_WhoAmI_NoTgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string CommandLine_WhoAmI_UserName {
            get {
                return ResourceManager.GetString("CommandLine_WhoAmI_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an unknown command. Try typing &apos;help&apos; for a list of all commands..
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
    }
}
